### ISSUE TITLE
Would like to see some examples

### ISSUE THREAD

**Issue by eason280711** [sum1afk/vsgSDL#1] opened 2022-07-23 09:53 UTC
Hello, I am a student who is learning to use vsg
Wondering if I can get some sample code using vsgSDL?

**Comment by sum1afk** [comment] 2022-07-31 04:56
For now you can see the readme, but I haven't made any real examples yet
I'll be getting to that soon and other important updates
Please take in mind vsgSDL is still in a very early state, but if there's a specific feature you want from SDL to be integrated (with VSG) feel free to request that here too

**Comment by eason280711** [comment] 2022-07-31 06:01
Thanks a lot, after that I had it working successfully, actually I was using vsgSDL for the multi-view ports and docking features in the imgui docking branch, which doesn't seem to work after I dug into how the WindowAdapter works So in the end I chose to rewirte vsg's native win32 window class to SDL windows class, your vsgSDL helped me a lot in the process! I'm really grateful. Although I ran into some troubles after the rewrite, I'm trying to deal with it as well. Thank you once again!

**Comment by sum1afk** [comment] 2022-07-31 06:25
vsgSDL was designed so far with usage of ImGui in mind, since I wanted my original project using it to use ImGui
If you want to know how to use that, in the pseudo-example in the readme "window.textInput =" was added to capture text input boxes from imgui SDL integration, but I wanted to separate the code from vsgSDL, since I don't want ImGui to be a dependency
I thought of making it a native part of vsgSDL, but decided not to since SDL can use a lot of resources and the implementation and input handling should probably be handled by the programmer
I'm glad it helped -- that's why I published it
I basically implemented the bare minimum and a very simple SDL Vulkan loader handler
Later I'll post working code, but you want window.textInput (vsgSDL window) from the readme, to be a function which calls ImGui io.AddInputCharactersUTF8() like this:
        `       window.textInput = [](const char text[SDL_TEXTINPUTEVENT_TEXT_SIZE]) {
            io.AddInputCharactersUTF8(text);
        };`
This is called in vsgSDL for the SDL event handling loop and switch, the case for text input somewhere, since I had found this to be the most effective way to allow the programmer to provide a callback to be used, since other attempts at implementing text handling with SDL and ImGui were unsuccessful 
Also be careful with the last parameter of window.create(), since it is very important for the SDL Vulkan loader (dynamic library)
If there are any bug fixes or problems, please post a request or however you do with github (I'm not very familiar, but I'll figure it out from a notification)

**Comment by eason280711** [comment] 2022-07-31 13:55
I did change a little thing, I will make it a request. But I want to explain my idea first, the first one is just a small change, I changed initSDLVulkan to call ` SDL_Vulkan_LoadLibrary(NULL)` if no path is entered . The reason for this is because I think SDL's default paths work well in my environment, another point to change is focusGained and focusLost, I found that after closing windows and reopening, the windows don't continue to render, so I pass window as a parameter to focusGained and focusLost so that they can set windowValid and windowVisible, which can solve the problem of black screen after closing the window. At the same time, I also wrote a CMakeList for vsgSDL, which works well on my computer , but I'm a newbie, I'm not sure if it will work in other people's environments, and I've also added a sample for vsgSDL, and modified the readme file a little bit, adding the sample and on windows setup step. Thanks to your work, I hope this little contribution can help you. For the imgui part, I did successfully run vsgiImGui and vsgSDL successfully, but some functions could not be used. The backend of ImGui defines struct ImGuiPlatformIO to implement multi-viewport, one of which ImGuiPlatformIO will operate is the created a new windows (multi-viewport is a function that can drag imgui objects inside the viewport out of the viewport), but what I do with vsgSDL and vsgImgui will be that when I drag the imgui object to the side of the window, A new SDL windows is generated (if SDL is selected as the backend), but the newly generated windows will be blank (without rendering anything) and cannot be dragged. Maybe I will think about how to make changes, currently I just rewrite vsg native windows class with SDL windows and it works well! Although it also caused some derivative problems. I will continue to research this.

**Comment by sum1afk** [comment] 2022-08-03 02:54
Oh that's right, I did add some code to handle SDL_Vulkan_LoadLibrary(NULL), but had never committed it. I had never made a CMake setup for the project, but I was considering it. I had just compiled it with my project. There definitely needs to be improvements and additions to SDL window event handling. I'll get to your pull request eventually and merge it regardless. Thank you. 

As of now vsgSDL probably has some compatibility problems with vsgImGui. For my project I had modified vsgImGui and made updates to use a newer version of ImGui (for vsgImGui). Like I said, still haven't decided how to handle this and make sure it's compatible or just integrated and links to the vsgImGui repository.

I'll look into your case usage for multi-viewports. Clarify if you need to but I'll put what I think your goals are in my own words:
An ImGui window (object) when snapped the the edge of the screen (viewport in SDL window), creates a new SDL window (viewport) when the ImGui backend is set to SDL
The SDL window will be created with flags like: borderless, draggable off, no renderer, and possibly other flags

I'd like to add these features to vsgSDL and make vsgImGui compatible.
Currently there are some major changes that will need to be made for that, but you've pointed out some important details to help identify the issues, so I appreciate that.

Originally I had based vsgSDL on VSG's native window, but then was able to understand how to use VSG window adapter to access third party windows (SDL). It's mostly about getting a handle to the right surface. I'd like to tell me more about what your goals are specifically because that gives me a clearer idea of what features you want implemented. It's a little ambiguous still. Maybe an Operating System type of interface for example, or something else entirely. Let me know more about what you want to do

**Comment by sum1afk** [comment] 2022-08-11 22:03
I accidentally closed this issue, but I want to leave it open until you respond, so I made sure it was reopened. I'll wait a while for a response before I close it. Take your time

**Comment by eason280711** [comment] 2022-08-12 15:48
Sorry for replying so late, I have been spending the last month researching and writing programs all day, and I actually like this kind of life lol, but I have to deal with some trivial things in life as a last resort.

Back to the topic, I want to use vsgSDL In my game engine project, I want to learn the architecture and concepts of the game engine through the method of implementation, I found vsg when I was learning about rendering and decided to use it. And I also modified vsgImGui to update it and use the Docking branch, maybe some compatibility issues made it not work correctly, so I switched to vsgSDL. Then comes the question I raised above.

In fact, I think it may not be entirely due to the compatibility of vsgSDL and vsgImGui that causes the function problem. When I use the native vsg windows, that is, win32 as the backend of imgui, it also fails to run successfully when I use the Docking branch of imgui. (But I'm not sure why, the official example does not provide win32 and vulkan, and I can't find the problem!)

Thank you for your works again!
By the way, would it be alright if I added you on discord or other chat platform? I'm a CS student studying game engines, and I would like to contact you in the future to ask questions and learn from you!

This is my email if you can, thanks!
eason280711@gmail.com

**Comment by sum1afk** [comment] 2022-08-15 13:32
Don't worry about it, take care of your health / mental health. It's top priority. Most importantly, enjoy what you're doing! I wanted to say that before continuing

The original purpose for vsgSDL is in something similar to a game engine, which probably isn't surprising. I think I had written in a Todo somewhere recently to make an ImGui branch for vsgSDL, but I haven't decided on that either because I don't really want to manage 2 branches for something would probably be commonly used as a feature (ImGui) by most programmers also using something like vsgSDL

My personal project which integrates ImGui with vsgSDL but it might be outdated now, and it probably was a little bit rigged in the first place, but it does "work".

If that's what you're curious about that I was doing
You can add me on discord: sum1#0457
I can't promise to be very responsive or knowledgeable, and there are many others who are much more helpful than me, but if you are just looking to make a friend to maybe work on projects with, then that's okay too -- as I said before, enjoy what you're doing

I'll keep your email in mind if needed

**Closed as completed** 2022-08-15 19:30 UTC
Labels: documentation
